"""Sample data for demos and tests, shaped like a generic fitness API
response (list of per-day JSON records) so it can be fed straight through
``api_adapter.build_weekly_health_data``.
"""

from __future__ import annotations

SAMPLE_API_RESPONSE: list[dict] = [
    {
        "date": "2026-07-13",
        "active_minutes": 22,
        "calories_in": 2100,
        "calories_out": 2300,
        "protein_g": 118,
        "carbs_g": 220,
        "fat_g": 70,
        "weight_lbs": 182.4,
        "height": 70,
        "age": 34,
        "gender": "male",
        "activity_level": "sedentary",
    },
    {
        "date": "2026-07-14",
        "active_minutes": 41,
        "calories_in": 2050,
        "calories_out": 2450,
        "protein_g": 145,
        "carbs_g": 200,
        "fat_g": 65,
        "weight_lbs": 182.1,
        "height": 70,
        "age": 34,
        "gender": "male",
        "activity_level": "moderate",
    },
    {
        "date": "2026-07-15",
        "active_minutes": 12,
        "calories_in": 2400,
        "calories_out": 2100,
        "protein_g": 95,
        "carbs_g": 280,
        "fat_g": 80,
        "weight_lbs": 182.6,
        "height": 70,
        "age": 34,
        "gender": "male",
        "activity_level": "sedentary",
    },
    {
        "date": "2026-07-16",
        "active_minutes": 35,
        "calories_in": 2000,
        "calories_out": 2380,
        "protein_g": 150,
        "carbs_g": 190,
        "fat_g": 62,
        "weight_lbs": 181.9,
        "height": 70,
        "age": 34,
        "gender": "male",
        "activity_level": "active",
    },
    {
        "date": "2026-07-17",
        "active_minutes": 28,
        "calories_in": 2150,
        "calories_out": 2280,
        "protein_g": 130,
        "carbs_g": 210,
        "fat_g": 72,
        "weight_lbs": 181.7,
        "height": 70,
        "age": 34,
        "gender": "male",
        "activity_level": "light",
    },
    {
        "date": "2026-07-18",
        "active_minutes": 52,
        "calories_in": 2200,
        "calories_out": 2600,
        "protein_g": 160,
        "carbs_g": 230,
        "fat_g": 68,
        "weight_lbs": 181.3,
        "height": 70,
        "age": 34,
        "gender": "male",
        "activity_level": "veryActive",
    },
    {
        "date": "2026-07-19",
        "active_minutes": 18,
        "calories_in": 2300,
        "calories_out": 2150,
        "protein_g": 110,
        "carbs_g": 260,
        "fat_g": 75,
        "weight_lbs": 181.5,
        "height": 70,
        "age": 34,
        "gender": "male",
        "activity_level": "light",
    },
]

# A sample "goals" record, shaped the way api_adapter.parse_goals expects.
SAMPLE_GOALS: dict = {
    "goal_type": "lose_weight",
    "target_weight_lbs": 175,
    "target_calories_in": 2100,
    "target_protein_g": 150,
    "target_carbs_g": 200,
    "target_fat_g": 70,
    "target_active_minutes": 30,
}